### ISSUE TITLE
Norbot page is down

### ISSUE THREAD

**Issue by Jaknil** [arockenberger/robotronikk#5]
On page 
https://github.com/arockenberger/robotronikk#about

The Norbot wiki link: 
http://norbot.net/wiki/index.php?title=User:Annika
has sadly rotted away and now leads to a spam page. Unclear if the wiki has moved or died.

**Comment by arockenberger** [comment]
Domain has expired. Will remove the link!

**Comment by arockenberger** [comment]
Updated and done!
